title: Varun Mohite
logo: /assets/img/logo.png
description: Welcome to my onlin resume showcasing my portfolio of projects, case studies and assignments compelted so far related to AI & ML.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
