title: Varun Mohite
logo: /assets/img/Designer.jfif
description: Welcome to my online resume showcasing my portfolio of projects, case studies and assignments completed so far related to AI & ML.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
