title: Varun Mohite
logo: /assets/img/IMG_20200105_193737.jpg
description: Welcome to my online resume showcasing my portfolio of projects, case studies and assignments compelted so far related to AI & ML.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
